/*
 * DO NOT EDIT THIS FILE BY HAND!  It is generated by MKfallback.sh.
 */

#include <curses.priv.h>

#include <tic.h>

/* fallback entries for: linux vt102 */
/* linux */

static char linux_alias_data[] = "linux|linux console";

static char linux_s_bel         [] = "\007";
static char linux_s_cr          [] = "\015";
static char linux_s_csr         [] = "\033[%i%p1%d;%p2%dr";
static char linux_s_tbc         [] = "\033[3g";
static char linux_s_clear       [] = "\033[H\033[J";
static char linux_s_el          [] = "\033[K";
static char linux_s_ed          [] = "\033[J";
static char linux_s_hpa         [] = "\033[%i%p1%dG";
static char linux_s_cup         [] = "\033[%i%p1%d;%p2%dH";
static char linux_s_cud1        [] = "\012";
static char linux_s_home        [] = "\033[H";
static char linux_s_civis       [] = "\033[?25l\033[?1c";
static char linux_s_cub1        [] = "\010";
static char linux_s_cnorm       [] = "\033[?25h\033[?0c";
static char linux_s_cuf1        [] = "\033[C";
static char linux_s_cuu1        [] = "\033[A";
static char linux_s_cvvis       [] = "\033[?25h\033[?8c";
static char linux_s_dch1        [] = "\033[P";
static char linux_s_dl1         [] = "\033[M";
static char linux_s_smacs       [] = "\033[11m";
static char linux_s_blink       [] = "\033[5m";
static char linux_s_bold        [] = "\033[1m";
static char linux_s_dim         [] = "\033[2m";
static char linux_s_smir        [] = "\033[4h";
static char linux_s_rev         [] = "\033[7m";
static char linux_s_smso        [] = "\033[7m";
static char linux_s_smul        [] = "\033[4m";
static char linux_s_ech         [] = "\033[%p1%dX";
static char linux_s_rmacs       [] = "\033[10m";
static char linux_s_sgr0        [] = "\033[0;10m";
static char linux_s_rmir        [] = "\033[4l";
static char linux_s_rmso        [] = "\033[27m";
static char linux_s_rmul        [] = "\033[24m";
static char linux_s_flash       [] = "\033[?5h\033[?5l$<200/>";
static char linux_s_ich1        [] = "\033[@";
static char linux_s_il1         [] = "\033[L";
static char linux_s_kbs         [] = "\177";
static char linux_s_kdch1       [] = "\033[3~";
static char linux_s_kcud1       [] = "\033[B";
static char linux_s_kf1         [] = "\033[[A";
static char linux_s_kf10        [] = "\033[21~";
static char linux_s_kf2         [] = "\033[[B";
static char linux_s_kf3         [] = "\033[[C";
static char linux_s_kf4         [] = "\033[[D";
static char linux_s_kf5         [] = "\033[[E";
static char linux_s_kf6         [] = "\033[17~";
static char linux_s_kf7         [] = "\033[18~";
static char linux_s_kf8         [] = "\033[19~";
static char linux_s_kf9         [] = "\033[20~";
static char linux_s_khome       [] = "\033[1~";
static char linux_s_kich1       [] = "\033[2~";
static char linux_s_kcub1       [] = "\033[D";
static char linux_s_knp         [] = "\033[6~";
static char linux_s_kpp         [] = "\033[5~";
static char linux_s_kcuf1       [] = "\033[C";
static char linux_s_kcuu1       [] = "\033[A";
static char linux_s_nel         [] = "\015\012";
static char linux_s_dch         [] = "\033[%p1%dP";
static char linux_s_dl          [] = "\033[%p1%dM";
static char linux_s_cud         [] = "\033[%p1%dB";
static char linux_s_ich         [] = "\033[%p1%d@";
static char linux_s_il          [] = "\033[%p1%dL";
static char linux_s_cub         [] = "\033[%p1%dD";
static char linux_s_cuf         [] = "\033[%p1%dC";
static char linux_s_cuu         [] = "\033[%p1%dA";
static char linux_s_rs1         [] = "\033c\033]R";
static char linux_s_rc          [] = "\0338";
static char linux_s_vpa         [] = "\033[%i%p1%dd";
static char linux_s_sc          [] = "\0337";
static char linux_s_ind         [] = "\012";
static char linux_s_ri          [] = "\033M";
static char linux_s_sgr         [] = "\033[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p6%t;1%;%?%p7%t;8%;%?%p9%t;11%;m";
static char linux_s_hts         [] = "\033H";
static char linux_s_ht          [] = "\011";
static char linux_s_kb2         [] = "\033[G";
static char linux_s_acsc        [] = "+\020,\021-\030.\0310\333`\004a\261f\370g\361h\260i\316j\331k\277l\332m\300n\305o~p\304q\304r\304s_t\303u\264v\301w\302x\263y\363z\362{\343|\330}\234~\376";
static char linux_s_kcbt        [] = "\033[Z";
static char linux_s_smam        [] = "\033[?7h";
static char linux_s_rmam        [] = "\033[?7l";
static char linux_s_kend        [] = "\033[4~";
static char linux_s_kspd        [] = "\032";
static char linux_s_kf11        [] = "\033[23~";
static char linux_s_kf12        [] = "\033[24~";
static char linux_s_kf13        [] = "\033[25~";
static char linux_s_kf14        [] = "\033[26~";
static char linux_s_kf15        [] = "\033[28~";
static char linux_s_kf16        [] = "\033[29~";
static char linux_s_kf17        [] = "\033[31~";
static char linux_s_kf18        [] = "\033[32~";
static char linux_s_kf19        [] = "\033[33~";
static char linux_s_kf20        [] = "\033[34~";
static char linux_s_el1         [] = "\033[1K";
static char linux_s_u6          [] = "\033[%i%d;%dR";
static char linux_s_u7          [] = "\033[6n";
static char linux_s_u8          [] = "\033[?6c";
static char linux_s_u9          [] = "\033[c";
static char linux_s_op          [] = "\033[39;49m";
static char linux_s_oc          [] = "\033]R";
static char linux_s_initc       [] = "\033]P%p1%x%p2%{255}%*%{1000}%/%02x%p3%{255}%*%{1000}%/%02x%p4%{255}%*%{1000}%/%02x";
static char linux_s_kmous       [] = "\033[M";
static char linux_s_setaf       [] = "\033[3%p1%dm";
static char linux_s_setab       [] = "\033[4%p1%dm";
static char linux_s_smpch       [] = "\033[11m";
static char linux_s_rmpch       [] = "\033[10m";

static char linux_bool_data[] = {
	/*   0: bw       */	FALSE,
	/*   1: am       */	TRUE,
	/*   2: xsb      */	FALSE,
	/*   3: xhp      */	FALSE,
	/*   4: xenl     */	TRUE,
	/*   5: eo       */	TRUE,
	/*   6: gn       */	FALSE,
	/*   7: hc       */	FALSE,
	/*   8: km       */	FALSE,
	/*   9: hs       */	FALSE,
	/*  10: in       */	FALSE,
	/*  11: da       */	FALSE,
	/*  12: db       */	FALSE,
	/*  13: mir      */	TRUE,
	/*  14: msgr     */	TRUE,
	/*  15: os       */	FALSE,
	/*  16: eslok    */	FALSE,
	/*  17: xt       */	FALSE,
	/*  18: hz       */	FALSE,
	/*  19: ul       */	FALSE,
	/*  20: xon      */	TRUE,
	/*  21: nxon     */	FALSE,
	/*  22: mc5i     */	FALSE,
	/*  23: chts     */	FALSE,
	/*  24: nrrmc    */	FALSE,
	/*  25: npc      */	FALSE,
	/*  26: ndscr    */	FALSE,
	/*  27: ccc      */	TRUE,
	/*  28: bce      */	TRUE,
	/*  29: hls      */	FALSE,
	/*  30: xhpa     */	FALSE,
	/*  31: crxm     */	FALSE,
	/*  32: daisy    */	FALSE,
	/*  33: xvpa     */	FALSE,
	/*  34: sam      */	FALSE,
	/*  35: cpix     */	FALSE,
	/*  36: lpix     */	FALSE,
	/*  37: OTbs     */	FALSE,
	/*  38: OTns     */	FALSE,
	/*  39: OTnc     */	FALSE,
	/*  40: OTMT     */	FALSE,
	/*  41: OTNL     */	FALSE,
	/*  42: OTpt     */	FALSE,
	/*  43: OTxr     */	FALSE,
};
static short linux_number_data[] = {
	/*   0: cols     */	ABSENT_NUMERIC,
	/*   1: it       */	8,
	/*   2: lines    */	ABSENT_NUMERIC,
	/*   3: lm       */	ABSENT_NUMERIC,
	/*   4: xmc      */	ABSENT_NUMERIC,
	/*   5: pb       */	ABSENT_NUMERIC,
	/*   6: vt       */	ABSENT_NUMERIC,
	/*   7: wsl      */	ABSENT_NUMERIC,
	/*   8: nlab     */	ABSENT_NUMERIC,
	/*   9: lh       */	ABSENT_NUMERIC,
	/*  10: lw       */	ABSENT_NUMERIC,
	/*  11: ma       */	ABSENT_NUMERIC,
	/*  12: wnum     */	ABSENT_NUMERIC,
	/*  13: colors   */	8,
	/*  14: pairs    */	64,
	/*  15: ncv      */	18,
	/*  16: bufsz    */	ABSENT_NUMERIC,
	/*  17: spinv    */	ABSENT_NUMERIC,
	/*  18: spinh    */	ABSENT_NUMERIC,
	/*  19: maddr    */	ABSENT_NUMERIC,
	/*  20: mjump    */	ABSENT_NUMERIC,
	/*  21: mcs      */	ABSENT_NUMERIC,
	/*  22: mls      */	ABSENT_NUMERIC,
	/*  23: npins    */	ABSENT_NUMERIC,
	/*  24: orc      */	ABSENT_NUMERIC,
	/*  25: orl      */	ABSENT_NUMERIC,
	/*  26: orhi     */	ABSENT_NUMERIC,
	/*  27: orvi     */	ABSENT_NUMERIC,
	/*  28: cps      */	ABSENT_NUMERIC,
	/*  29: widcs    */	ABSENT_NUMERIC,
	/*  30: btns     */	ABSENT_NUMERIC,
	/*  31: bitwin   */	ABSENT_NUMERIC,
	/*  32: bitype   */	ABSENT_NUMERIC,
	/*  33: OTug     */	ABSENT_NUMERIC,
	/*  34: OTdC     */	ABSENT_NUMERIC,
	/*  35: OTdN     */	ABSENT_NUMERIC,
	/*  36: OTdB     */	ABSENT_NUMERIC,
	/*  37: OTdT     */	ABSENT_NUMERIC,
	/*  38: OTkn     */	ABSENT_NUMERIC,
};
static char * linux_string_data[] = {
	/*   0: cbt      */	ABSENT_STRING,
	/*   1: bel      */	linux_s_bel,
	/*   2: cr       */	linux_s_cr,
	/*   3: csr      */	linux_s_csr,
	/*   4: tbc      */	linux_s_tbc,
	/*   5: clear    */	linux_s_clear,
	/*   6: el       */	linux_s_el,
	/*   7: ed       */	linux_s_ed,
	/*   8: hpa      */	linux_s_hpa,
	/*   9: cmdch    */	ABSENT_STRING,
	/*  10: cup      */	linux_s_cup,
	/*  11: cud1     */	linux_s_cud1,
	/*  12: home     */	linux_s_home,
	/*  13: civis    */	linux_s_civis,
	/*  14: cub1     */	linux_s_cub1,
	/*  15: mrcup    */	ABSENT_STRING,
	/*  16: cnorm    */	linux_s_cnorm,
	/*  17: cuf1     */	linux_s_cuf1,
	/*  18: ll       */	ABSENT_STRING,
	/*  19: cuu1     */	linux_s_cuu1,
	/*  20: cvvis    */	linux_s_cvvis,
	/*  21: dch1     */	linux_s_dch1,
	/*  22: dl1      */	linux_s_dl1,
	/*  23: dsl      */	ABSENT_STRING,
	/*  24: hd       */	ABSENT_STRING,
	/*  25: smacs    */	linux_s_smacs,
	/*  26: blink    */	linux_s_blink,
	/*  27: bold     */	linux_s_bold,
	/*  28: smcup    */	ABSENT_STRING,
	/*  29: smdc     */	ABSENT_STRING,
	/*  30: dim      */	linux_s_dim,
	/*  31: smir     */	linux_s_smir,
	/*  32: invis    */	ABSENT_STRING,
	/*  33: prot     */	ABSENT_STRING,
	/*  34: rev      */	linux_s_rev,
	/*  35: smso     */	linux_s_smso,
	/*  36: smul     */	linux_s_smul,
	/*  37: ech      */	linux_s_ech,
	/*  38: rmacs    */	linux_s_rmacs,
	/*  39: sgr0     */	linux_s_sgr0,
	/*  40: rmcup    */	ABSENT_STRING,
	/*  41: rmdc     */	ABSENT_STRING,
	/*  42: rmir     */	linux_s_rmir,
	/*  43: rmso     */	linux_s_rmso,
	/*  44: rmul     */	linux_s_rmul,
	/*  45: flash    */	linux_s_flash,
	/*  46: ff       */	ABSENT_STRING,
	/*  47: fsl      */	ABSENT_STRING,
	/*  48: is1      */	ABSENT_STRING,
	/*  49: is2      */	ABSENT_STRING,
	/*  50: is3      */	ABSENT_STRING,
	/*  51: if       */	ABSENT_STRING,
	/*  52: ich1     */	linux_s_ich1,
	/*  53: il1      */	linux_s_il1,
	/*  54: ip       */	ABSENT_STRING,
	/*  55: kbs      */	linux_s_kbs,
	/*  56: ktbc     */	ABSENT_STRING,
	/*  57: kclr     */	ABSENT_STRING,
	/*  58: kctab    */	ABSENT_STRING,
	/*  59: kdch1    */	linux_s_kdch1,
	/*  60: kdl1     */	ABSENT_STRING,
	/*  61: kcud1    */	linux_s_kcud1,
	/*  62: krmir    */	ABSENT_STRING,
	/*  63: kel      */	ABSENT_STRING,
	/*  64: ked      */	ABSENT_STRING,
	/*  65: kf0      */	ABSENT_STRING,
	/*  66: kf1      */	linux_s_kf1,
	/*  67: kf10     */	linux_s_kf10,
	/*  68: kf2      */	linux_s_kf2,
	/*  69: kf3      */	linux_s_kf3,
	/*  70: kf4      */	linux_s_kf4,
	/*  71: kf5      */	linux_s_kf5,
	/*  72: kf6      */	linux_s_kf6,
	/*  73: kf7      */	linux_s_kf7,
	/*  74: kf8      */	linux_s_kf8,
	/*  75: kf9      */	linux_s_kf9,
	/*  76: khome    */	linux_s_khome,
	/*  77: kich1    */	linux_s_kich1,
	/*  78: kil1     */	ABSENT_STRING,
	/*  79: kcub1    */	linux_s_kcub1,
	/*  80: kll      */	ABSENT_STRING,
	/*  81: knp      */	linux_s_knp,
	/*  82: kpp      */	linux_s_kpp,
	/*  83: kcuf1    */	linux_s_kcuf1,
	/*  84: kind     */	ABSENT_STRING,
	/*  85: kri      */	ABSENT_STRING,
	/*  86: khts     */	ABSENT_STRING,
	/*  87: kcuu1    */	linux_s_kcuu1,
	/*  88: rmkx     */	ABSENT_STRING,
	/*  89: smkx     */	ABSENT_STRING,
	/*  90: lf0      */	ABSENT_STRING,
	/*  91: lf1      */	ABSENT_STRING,
	/*  92: lf10     */	ABSENT_STRING,
	/*  93: lf2      */	ABSENT_STRING,
	/*  94: lf3      */	ABSENT_STRING,
	/*  95: lf4      */	ABSENT_STRING,
	/*  96: lf5      */	ABSENT_STRING,
	/*  97: lf6      */	ABSENT_STRING,
	/*  98: lf7      */	ABSENT_STRING,
	/*  99: lf8      */	ABSENT_STRING,
	/* 100: lf9      */	ABSENT_STRING,
	/* 101: rmm      */	ABSENT_STRING,
	/* 102: smm      */	ABSENT_STRING,
	/* 103: nel      */	linux_s_nel,
	/* 104: pad      */	ABSENT_STRING,
	/* 105: dch      */	linux_s_dch,
	/* 106: dl       */	linux_s_dl,
	/* 107: cud      */	linux_s_cud,
	/* 108: ich      */	linux_s_ich,
	/* 109: indn     */	ABSENT_STRING,
	/* 110: il       */	linux_s_il,
	/* 111: cub      */	linux_s_cub,
	/* 112: cuf      */	linux_s_cuf,
	/* 113: rin      */	ABSENT_STRING,
	/* 114: cuu      */	linux_s_cuu,
	/* 115: pfkey    */	ABSENT_STRING,
	/* 116: pfloc    */	ABSENT_STRING,
	/* 117: pfx      */	ABSENT_STRING,
	/* 118: mc0      */	ABSENT_STRING,
	/* 119: mc4      */	ABSENT_STRING,
	/* 120: mc5      */	ABSENT_STRING,
	/* 121: rep      */	ABSENT_STRING,
	/* 122: rs1      */	linux_s_rs1,
	/* 123: rs2      */	ABSENT_STRING,
	/* 124: rs3      */	ABSENT_STRING,
	/* 125: rf       */	ABSENT_STRING,
	/* 126: rc       */	linux_s_rc,
	/* 127: vpa      */	linux_s_vpa,
	/* 128: sc       */	linux_s_sc,
	/* 129: ind      */	linux_s_ind,
	/* 130: ri       */	linux_s_ri,
	/* 131: sgr      */	linux_s_sgr,
	/* 132: hts      */	linux_s_hts,
	/* 133: wind     */	ABSENT_STRING,
	/* 134: ht       */	linux_s_ht,
	/* 135: tsl      */	ABSENT_STRING,
	/* 136: uc       */	ABSENT_STRING,
	/* 137: hu       */	ABSENT_STRING,
	/* 138: iprog    */	ABSENT_STRING,
	/* 139: ka1      */	ABSENT_STRING,
	/* 140: ka3      */	ABSENT_STRING,
	/* 141: kb2      */	linux_s_kb2,
	/* 142: kc1      */	ABSENT_STRING,
	/* 143: kc3      */	ABSENT_STRING,
	/* 144: mc5p     */	ABSENT_STRING,
	/* 145: rmp      */	ABSENT_STRING,
	/* 146: acsc     */	linux_s_acsc,
	/* 147: pln      */	ABSENT_STRING,
	/* 148: kcbt     */	linux_s_kcbt,
	/* 149: smxon    */	ABSENT_STRING,
	/* 150: rmxon    */	ABSENT_STRING,
	/* 151: smam     */	linux_s_smam,
	/* 152: rmam     */	linux_s_rmam,
	/* 153: xonc     */	ABSENT_STRING,
	/* 154: xoffc    */	ABSENT_STRING,
	/* 155: enacs    */	ABSENT_STRING,
	/* 156: smln     */	ABSENT_STRING,
	/* 157: rmln     */	ABSENT_STRING,
	/* 158: kbeg     */	ABSENT_STRING,
	/* 159: kcan     */	ABSENT_STRING,
	/* 160: kclo     */	ABSENT_STRING,
	/* 161: kcmd     */	ABSENT_STRING,
	/* 162: kcpy     */	ABSENT_STRING,
	/* 163: kcrt     */	ABSENT_STRING,
	/* 164: kend     */	linux_s_kend,
	/* 165: kent     */	ABSENT_STRING,
	/* 166: kext     */	ABSENT_STRING,
	/* 167: kfnd     */	ABSENT_STRING,
	/* 168: khlp     */	ABSENT_STRING,
	/* 169: kmrk     */	ABSENT_STRING,
	/* 170: kmsg     */	ABSENT_STRING,
	/* 171: kmov     */	ABSENT_STRING,
	/* 172: knxt     */	ABSENT_STRING,
	/* 173: kopn     */	ABSENT_STRING,
	/* 174: kopt     */	ABSENT_STRING,
	/* 175: kprv     */	ABSENT_STRING,
	/* 176: kprt     */	ABSENT_STRING,
	/* 177: krdo     */	ABSENT_STRING,
	/* 178: kref     */	ABSENT_STRING,
	/* 179: krfr     */	ABSENT_STRING,
	/* 180: krpl     */	ABSENT_STRING,
	/* 181: krst     */	ABSENT_STRING,
	/* 182: kres     */	ABSENT_STRING,
	/* 183: ksav     */	ABSENT_STRING,
	/* 184: kspd     */	linux_s_kspd,
	/* 185: kund     */	ABSENT_STRING,
	/* 186: kBEG     */	ABSENT_STRING,
	/* 187: kCAN     */	ABSENT_STRING,
	/* 188: kCMD     */	ABSENT_STRING,
	/* 189: kCPY     */	ABSENT_STRING,
	/* 190: kCRT     */	ABSENT_STRING,
	/* 191: kDC      */	ABSENT_STRING,
	/* 192: kDL      */	ABSENT_STRING,
	/* 193: kslt     */	ABSENT_STRING,
	/* 194: kEND     */	ABSENT_STRING,
	/* 195: kEOL     */	ABSENT_STRING,
	/* 196: kEXT     */	ABSENT_STRING,
	/* 197: kFND     */	ABSENT_STRING,
	/* 198: kHLP     */	ABSENT_STRING,
	/* 199: kHOM     */	ABSENT_STRING,
	/* 200: kIC      */	ABSENT_STRING,
	/* 201: kLFT     */	ABSENT_STRING,
	/* 202: kMSG     */	ABSENT_STRING,
	/* 203: kMOV     */	ABSENT_STRING,
	/* 204: kNXT     */	ABSENT_STRING,
	/* 205: kOPT     */	ABSENT_STRING,
	/* 206: kPRV     */	ABSENT_STRING,
	/* 207: kPRT     */	ABSENT_STRING,
	/* 208: kRDO     */	ABSENT_STRING,
	/* 209: kRPL     */	ABSENT_STRING,
	/* 210: kRIT     */	ABSENT_STRING,
	/* 211: kRES     */	ABSENT_STRING,
	/* 212: kSAV     */	ABSENT_STRING,
	/* 213: kSPD     */	ABSENT_STRING,
	/* 214: kUND     */	ABSENT_STRING,
	/* 215: rfi      */	ABSENT_STRING,
	/* 216: kf11     */	linux_s_kf11,
	/* 217: kf12     */	linux_s_kf12,
	/* 218: kf13     */	linux_s_kf13,
	/* 219: kf14     */	linux_s_kf14,
	/* 220: kf15     */	linux_s_kf15,
	/* 221: kf16     */	linux_s_kf16,
	/* 222: kf17     */	linux_s_kf17,
	/* 223: kf18     */	linux_s_kf18,
	/* 224: kf19     */	linux_s_kf19,
	/* 225: kf20     */	linux_s_kf20,
	/* 226: kf21     */	ABSENT_STRING,
	/* 227: kf22     */	ABSENT_STRING,
	/* 228: kf23     */	ABSENT_STRING,
	/* 229: kf24     */	ABSENT_STRING,
	/* 230: kf25     */	ABSENT_STRING,
	/* 231: kf26     */	ABSENT_STRING,
	/* 232: kf27     */	ABSENT_STRING,
	/* 233: kf28     */	ABSENT_STRING,
	/* 234: kf29     */	ABSENT_STRING,
	/* 235: kf30     */	ABSENT_STRING,
	/* 236: kf31     */	ABSENT_STRING,
	/* 237: kf32     */	ABSENT_STRING,
	/* 238: kf33     */	ABSENT_STRING,
	/* 239: kf34     */	ABSENT_STRING,
	/* 240: kf35     */	ABSENT_STRING,
	/* 241: kf36     */	ABSENT_STRING,
	/* 242: kf37     */	ABSENT_STRING,
	/* 243: kf38     */	ABSENT_STRING,
	/* 244: kf39     */	ABSENT_STRING,
	/* 245: kf40     */	ABSENT_STRING,
	/* 246: kf41     */	ABSENT_STRING,
	/* 247: kf42     */	ABSENT_STRING,
	/* 248: kf43     */	ABSENT_STRING,
	/* 249: kf44     */	ABSENT_STRING,
	/* 250: kf45     */	ABSENT_STRING,
	/* 251: kf46     */	ABSENT_STRING,
	/* 252: kf47     */	ABSENT_STRING,
	/* 253: kf48     */	ABSENT_STRING,
	/* 254: kf49     */	ABSENT_STRING,
	/* 255: kf50     */	ABSENT_STRING,
	/* 256: kf51     */	ABSENT_STRING,
	/* 257: kf52     */	ABSENT_STRING,
	/* 258: kf53     */	ABSENT_STRING,
	/* 259: kf54     */	ABSENT_STRING,
	/* 260: kf55     */	ABSENT_STRING,
	/* 261: kf56     */	ABSENT_STRING,
	/* 262: kf57     */	ABSENT_STRING,
	/* 263: kf58     */	ABSENT_STRING,
	/* 264: kf59     */	ABSENT_STRING,
	/* 265: kf60     */	ABSENT_STRING,
	/* 266: kf61     */	ABSENT_STRING,
	/* 267: kf62     */	ABSENT_STRING,
	/* 268: kf63     */	ABSENT_STRING,
	/* 269: el1      */	linux_s_el1,
	/* 270: mgc      */	ABSENT_STRING,
	/* 271: smgl     */	ABSENT_STRING,
	/* 272: smgr     */	ABSENT_STRING,
	/* 273: fln      */	ABSENT_STRING,
	/* 274: sclk     */	ABSENT_STRING,
	/* 275: dclk     */	ABSENT_STRING,
	/* 276: rmclk    */	ABSENT_STRING,
	/* 277: cwin     */	ABSENT_STRING,
	/* 278: wingo    */	ABSENT_STRING,
	/* 279: hup      */	ABSENT_STRING,
	/* 280: dial     */	ABSENT_STRING,
	/* 281: qdial    */	ABSENT_STRING,
	/* 282: tone     */	ABSENT_STRING,
	/* 283: pulse    */	ABSENT_STRING,
	/* 284: hook     */	ABSENT_STRING,
	/* 285: pause    */	ABSENT_STRING,
	/* 286: wait     */	ABSENT_STRING,
	/* 287: u0       */	ABSENT_STRING,
	/* 288: u1       */	ABSENT_STRING,
	/* 289: u2       */	ABSENT_STRING,
	/* 290: u3       */	ABSENT_STRING,
	/* 291: u4       */	ABSENT_STRING,
	/* 292: u5       */	ABSENT_STRING,
	/* 293: u6       */	linux_s_u6,
	/* 294: u7       */	linux_s_u7,
	/* 295: u8       */	linux_s_u8,
	/* 296: u9       */	linux_s_u9,
	/* 297: op       */	linux_s_op,
	/* 298: oc       */	linux_s_oc,
	/* 299: initc    */	linux_s_initc,
	/* 300: initp    */	ABSENT_STRING,
	/* 301: scp      */	ABSENT_STRING,
	/* 302: setf     */	ABSENT_STRING,
	/* 303: setb     */	ABSENT_STRING,
	/* 304: cpi      */	ABSENT_STRING,
	/* 305: lpi      */	ABSENT_STRING,
	/* 306: chr      */	ABSENT_STRING,
	/* 307: cvr      */	ABSENT_STRING,
	/* 308: defc     */	ABSENT_STRING,
	/* 309: swidm    */	ABSENT_STRING,
	/* 310: sdrfq    */	ABSENT_STRING,
	/* 311: sitm     */	ABSENT_STRING,
	/* 312: slm      */	ABSENT_STRING,
	/* 313: smicm    */	ABSENT_STRING,
	/* 314: snlq     */	ABSENT_STRING,
	/* 315: snrmq    */	ABSENT_STRING,
	/* 316: sshm     */	ABSENT_STRING,
	/* 317: ssubm    */	ABSENT_STRING,
	/* 318: ssupm    */	ABSENT_STRING,
	/* 319: sum      */	ABSENT_STRING,
	/* 320: rwidm    */	ABSENT_STRING,
	/* 321: ritm     */	ABSENT_STRING,
	/* 322: rlm      */	ABSENT_STRING,
	/* 323: rmicm    */	ABSENT_STRING,
	/* 324: rshm     */	ABSENT_STRING,
	/* 325: rsubm    */	ABSENT_STRING,
	/* 326: rsupm    */	ABSENT_STRING,
	/* 327: rum      */	ABSENT_STRING,
	/* 328: mhpa     */	ABSENT_STRING,
	/* 329: mcud1    */	ABSENT_STRING,
	/* 330: mcub1    */	ABSENT_STRING,
	/* 331: mcuf1    */	ABSENT_STRING,
	/* 332: mvpa     */	ABSENT_STRING,
	/* 333: mcuu1    */	ABSENT_STRING,
	/* 334: porder   */	ABSENT_STRING,
	/* 335: mcud     */	ABSENT_STRING,
	/* 336: mcub     */	ABSENT_STRING,
	/* 337: mcuf     */	ABSENT_STRING,
	/* 338: mcuu     */	ABSENT_STRING,
	/* 339: scs      */	ABSENT_STRING,
	/* 340: smgb     */	ABSENT_STRING,
	/* 341: smgbp    */	ABSENT_STRING,
	/* 342: smglp    */	ABSENT_STRING,
	/* 343: smgrp    */	ABSENT_STRING,
	/* 344: smgt     */	ABSENT_STRING,
	/* 345: smgtp    */	ABSENT_STRING,
	/* 346: sbim     */	ABSENT_STRING,
	/* 347: scsd     */	ABSENT_STRING,
	/* 348: rbim     */	ABSENT_STRING,
	/* 349: rcsd     */	ABSENT_STRING,
	/* 350: subcs    */	ABSENT_STRING,
	/* 351: supcs    */	ABSENT_STRING,
	/* 352: docr     */	ABSENT_STRING,
	/* 353: zerom    */	ABSENT_STRING,
	/* 354: csnm     */	ABSENT_STRING,
	/* 355: kmous    */	linux_s_kmous,
	/* 356: minfo    */	ABSENT_STRING,
	/* 357: reqmp    */	ABSENT_STRING,
	/* 358: getm     */	ABSENT_STRING,
	/* 359: setaf    */	linux_s_setaf,
	/* 360: setab    */	linux_s_setab,
	/* 361: pfxl     */	ABSENT_STRING,
	/* 362: devt     */	ABSENT_STRING,
	/* 363: csin     */	ABSENT_STRING,
	/* 364: s0ds     */	ABSENT_STRING,
	/* 365: s1ds     */	ABSENT_STRING,
	/* 366: s2ds     */	ABSENT_STRING,
	/* 367: s3ds     */	ABSENT_STRING,
	/* 368: smglr    */	ABSENT_STRING,
	/* 369: smgtb    */	ABSENT_STRING,
	/* 370: birep    */	ABSENT_STRING,
	/* 371: binel    */	ABSENT_STRING,
	/* 372: bicr     */	ABSENT_STRING,
	/* 373: colornm  */	ABSENT_STRING,
	/* 374: defbi    */	ABSENT_STRING,
	/* 375: endbi    */	ABSENT_STRING,
	/* 376: setcolor */	ABSENT_STRING,
	/* 377: slines   */	ABSENT_STRING,
	/* 378: dispc    */	ABSENT_STRING,
	/* 379: smpch    */	linux_s_smpch,
	/* 380: rmpch    */	linux_s_rmpch,
	/* 381: smsc     */	ABSENT_STRING,
	/* 382: rmsc     */	ABSENT_STRING,
	/* 383: pctrm    */	ABSENT_STRING,
	/* 384: scesc    */	ABSENT_STRING,
	/* 385: scesa    */	ABSENT_STRING,
	/* 386: ehhlm    */	ABSENT_STRING,
	/* 387: elhlm    */	ABSENT_STRING,
	/* 388: elohlm   */	ABSENT_STRING,
	/* 389: erhlm    */	ABSENT_STRING,
	/* 390: ethlm    */	ABSENT_STRING,
	/* 391: evhlm    */	ABSENT_STRING,
	/* 392: sgr1     */	ABSENT_STRING,
	/* 393: slength  */	ABSENT_STRING,
	/* 394: OTi2     */	ABSENT_STRING,
	/* 395: OTrs     */	ABSENT_STRING,
	/* 396: OTnl     */	ABSENT_STRING,
	/* 397: OTbc     */	ABSENT_STRING,
	/* 398: OTko     */	ABSENT_STRING,
	/* 399: OTma     */	ABSENT_STRING,
	/* 400: OTG2     */	ABSENT_STRING,
	/* 401: OTG3     */	ABSENT_STRING,
	/* 402: OTG1     */	ABSENT_STRING,
	/* 403: OTG4     */	ABSENT_STRING,
	/* 404: OTGR     */	ABSENT_STRING,
	/* 405: OTGL     */	ABSENT_STRING,
	/* 406: OTGU     */	ABSENT_STRING,
	/* 407: OTGD     */	ABSENT_STRING,
	/* 408: OTGH     */	ABSENT_STRING,
	/* 409: OTGV     */	ABSENT_STRING,
	/* 410: OTGC     */	ABSENT_STRING,
	/* 411: meml     */	ABSENT_STRING,
	/* 412: memu     */	ABSENT_STRING,
	/* 413: box1     */	ABSENT_STRING,
};
/* vt102 */

static char vt102_alias_data[] = "vt102|dec vt102";

static char vt102_s_bel         [] = "\007";
static char vt102_s_cr          [] = "\015";
static char vt102_s_csr         [] = "\033[%i%p1%d;%p2%dr";
static char vt102_s_tbc         [] = "\033[3g";
static char vt102_s_clear       [] = "\033[H\033[J$<50>";
static char vt102_s_el          [] = "\033[K$<3>";
static char vt102_s_ed          [] = "\033[J$<50>";
static char vt102_s_cup         [] = "\033[%i%p1%d;%p2%dH$<5>";
static char vt102_s_cud1        [] = "\012";
static char vt102_s_home        [] = "\033[H";
static char vt102_s_cub1        [] = "\010";
static char vt102_s_cuf1        [] = "\033[C$<2>";
static char vt102_s_cuu1        [] = "\033[A$<2>";
static char vt102_s_dch1        [] = "\033[P";
static char vt102_s_dl1         [] = "\033[M";
static char vt102_s_smacs       [] = "\016";
static char vt102_s_blink       [] = "\033[5m$<2>";
static char vt102_s_bold        [] = "\033[1m$<2>";
static char vt102_s_smir        [] = "\033[4h";
static char vt102_s_rev         [] = "\033[7m$<2>";
static char vt102_s_smso        [] = "\033[7m$<2>";
static char vt102_s_smul        [] = "\033[4m$<2>";
static char vt102_s_rmacs       [] = "\017";
static char vt102_s_sgr0        [] = "\033[m\017$<2>";
static char vt102_s_rmir        [] = "\033[4l";
static char vt102_s_rmso        [] = "\033[m$<2>";
static char vt102_s_rmul        [] = "\033[m$<2>";
static char vt102_s_il1         [] = "\033[L";
static char vt102_s_kbs         [] = "\010";
static char vt102_s_kcud1       [] = "\033OB";
static char vt102_s_kf0         [] = "\033Oy";
static char vt102_s_kf1         [] = "\033OP";
static char vt102_s_kf10        [] = "\033Ox";
static char vt102_s_kf2         [] = "\033OQ";
static char vt102_s_kf3         [] = "\033OR";
static char vt102_s_kf4         [] = "\033OS";
static char vt102_s_kf5         [] = "\033Ot";
static char vt102_s_kf6         [] = "\033Ou";
static char vt102_s_kf7         [] = "\033Ov";
static char vt102_s_kf8         [] = "\033Ol";
static char vt102_s_kf9         [] = "\033Ow";
static char vt102_s_kcub1       [] = "\033OD";
static char vt102_s_kcuf1       [] = "\033OC";
static char vt102_s_kcuu1       [] = "\033OA";
static char vt102_s_rmkx        [] = "\033[?1l\033>";
static char vt102_s_smkx        [] = "\033[?1h\033=";
static char vt102_s_lf1         [] = "pf1";
static char vt102_s_lf2         [] = "pf2";
static char vt102_s_lf3         [] = "pf3";
static char vt102_s_lf4         [] = "pf4";
static char vt102_s_cud         [] = "\033[%p1%dB";
static char vt102_s_cub         [] = "\033[%p1%dD";
static char vt102_s_cuf         [] = "\033[%p1%dC";
static char vt102_s_cuu         [] = "\033[%p1%dA";
static char vt102_s_mc0         [] = "\033[0i";
static char vt102_s_mc4         [] = "\033[4i";
static char vt102_s_mc5         [] = "\033[5i";
static char vt102_s_rs2         [] = "\033>\033[?3l\033[?4l\033[?5l\033[?7h\033[?8h";
static char vt102_s_rc          [] = "\0338";
static char vt102_s_sc          [] = "\0337";
static char vt102_s_ind         [] = "\012";
static char vt102_s_ri          [] = "\033M$<5>";
static char vt102_s_sgr         [] = "\033[0%?%p1%p6%|%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;m%?%p9%t\016%e\017%;$<2>";
static char vt102_s_hts         [] = "\033H";
static char vt102_s_ht          [] = "\011";
static char vt102_s_ka1         [] = "\033Oq";
static char vt102_s_ka3         [] = "\033Os";
static char vt102_s_kb2         [] = "\033Or";
static char vt102_s_kc1         [] = "\033Op";
static char vt102_s_kc3         [] = "\033On";
static char vt102_s_acsc        [] = "``aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~";
static char vt102_s_smam        [] = "\033[?7h";
static char vt102_s_rmam        [] = "\033[?7l";
static char vt102_s_enacs       [] = "\033(B\033)0";
static char vt102_s_kent        [] = "\033OM";
static char vt102_s_el1         [] = "\033[1K$<3>";

static char vt102_bool_data[] = {
	/*   0: bw       */	FALSE,
	/*   1: am       */	TRUE,
	/*   2: xsb      */	FALSE,
	/*   3: xhp      */	FALSE,
	/*   4: xenl     */	TRUE,
	/*   5: eo       */	FALSE,
	/*   6: gn       */	FALSE,
	/*   7: hc       */	FALSE,
	/*   8: km       */	FALSE,
	/*   9: hs       */	FALSE,
	/*  10: in       */	FALSE,
	/*  11: da       */	FALSE,
	/*  12: db       */	FALSE,
	/*  13: mir      */	FALSE,
	/*  14: msgr     */	TRUE,
	/*  15: os       */	FALSE,
	/*  16: eslok    */	FALSE,
	/*  17: xt       */	FALSE,
	/*  18: hz       */	FALSE,
	/*  19: ul       */	FALSE,
	/*  20: xon      */	TRUE,
	/*  21: nxon     */	FALSE,
	/*  22: mc5i     */	TRUE,
	/*  23: chts     */	FALSE,
	/*  24: nrrmc    */	FALSE,
	/*  25: npc      */	FALSE,
	/*  26: ndscr    */	FALSE,
	/*  27: ccc      */	FALSE,
	/*  28: bce      */	FALSE,
	/*  29: hls      */	FALSE,
	/*  30: xhpa     */	FALSE,
	/*  31: crxm     */	FALSE,
	/*  32: daisy    */	FALSE,
	/*  33: xvpa     */	FALSE,
	/*  34: sam      */	FALSE,
	/*  35: cpix     */	FALSE,
	/*  36: lpix     */	FALSE,
	/*  37: OTbs     */	TRUE,
	/*  38: OTns     */	FALSE,
	/*  39: OTnc     */	FALSE,
	/*  40: OTMT     */	FALSE,
	/*  41: OTNL     */	FALSE,
	/*  42: OTpt     */	FALSE,
	/*  43: OTxr     */	FALSE,
};
static short vt102_number_data[] = {
	/*   0: cols     */	80,
	/*   1: it       */	8,
	/*   2: lines    */	24,
	/*   3: lm       */	ABSENT_NUMERIC,
	/*   4: xmc      */	ABSENT_NUMERIC,
	/*   5: pb       */	ABSENT_NUMERIC,
	/*   6: vt       */	3,
	/*   7: wsl      */	ABSENT_NUMERIC,
	/*   8: nlab     */	ABSENT_NUMERIC,
	/*   9: lh       */	ABSENT_NUMERIC,
	/*  10: lw       */	ABSENT_NUMERIC,
	/*  11: ma       */	ABSENT_NUMERIC,
	/*  12: wnum     */	ABSENT_NUMERIC,
	/*  13: colors   */	ABSENT_NUMERIC,
	/*  14: pairs    */	ABSENT_NUMERIC,
	/*  15: ncv      */	ABSENT_NUMERIC,
	/*  16: bufsz    */	ABSENT_NUMERIC,
	/*  17: spinv    */	ABSENT_NUMERIC,
	/*  18: spinh    */	ABSENT_NUMERIC,
	/*  19: maddr    */	ABSENT_NUMERIC,
	/*  20: mjump    */	ABSENT_NUMERIC,
	/*  21: mcs      */	ABSENT_NUMERIC,
	/*  22: mls      */	ABSENT_NUMERIC,
	/*  23: npins    */	ABSENT_NUMERIC,
	/*  24: orc      */	ABSENT_NUMERIC,
	/*  25: orl      */	ABSENT_NUMERIC,
	/*  26: orhi     */	ABSENT_NUMERIC,
	/*  27: orvi     */	ABSENT_NUMERIC,
	/*  28: cps      */	ABSENT_NUMERIC,
	/*  29: widcs    */	ABSENT_NUMERIC,
	/*  30: btns     */	ABSENT_NUMERIC,
	/*  31: bitwin   */	ABSENT_NUMERIC,
	/*  32: bitype   */	ABSENT_NUMERIC,
	/*  33: OTug     */	ABSENT_NUMERIC,
	/*  34: OTdC     */	ABSENT_NUMERIC,
	/*  35: OTdN     */	ABSENT_NUMERIC,
	/*  36: OTdB     */	ABSENT_NUMERIC,
	/*  37: OTdT     */	ABSENT_NUMERIC,
	/*  38: OTkn     */	ABSENT_NUMERIC,
};
static char * vt102_string_data[] = {
	/*   0: cbt      */	ABSENT_STRING,
	/*   1: bel      */	vt102_s_bel,
	/*   2: cr       */	vt102_s_cr,
	/*   3: csr      */	vt102_s_csr,
	/*   4: tbc      */	vt102_s_tbc,
	/*   5: clear    */	vt102_s_clear,
	/*   6: el       */	vt102_s_el,
	/*   7: ed       */	vt102_s_ed,
	/*   8: hpa      */	ABSENT_STRING,
	/*   9: cmdch    */	ABSENT_STRING,
	/*  10: cup      */	vt102_s_cup,
	/*  11: cud1     */	vt102_s_cud1,
	/*  12: home     */	vt102_s_home,
	/*  13: civis    */	ABSENT_STRING,
	/*  14: cub1     */	vt102_s_cub1,
	/*  15: mrcup    */	ABSENT_STRING,
	/*  16: cnorm    */	ABSENT_STRING,
	/*  17: cuf1     */	vt102_s_cuf1,
	/*  18: ll       */	ABSENT_STRING,
	/*  19: cuu1     */	vt102_s_cuu1,
	/*  20: cvvis    */	ABSENT_STRING,
	/*  21: dch1     */	vt102_s_dch1,
	/*  22: dl1      */	vt102_s_dl1,
	/*  23: dsl      */	ABSENT_STRING,
	/*  24: hd       */	ABSENT_STRING,
	/*  25: smacs    */	vt102_s_smacs,
	/*  26: blink    */	vt102_s_blink,
	/*  27: bold     */	vt102_s_bold,
	/*  28: smcup    */	ABSENT_STRING,
	/*  29: smdc     */	ABSENT_STRING,
	/*  30: dim      */	ABSENT_STRING,
	/*  31: smir     */	vt102_s_smir,
	/*  32: invis    */	ABSENT_STRING,
	/*  33: prot     */	ABSENT_STRING,
	/*  34: rev      */	vt102_s_rev,
	/*  35: smso     */	vt102_s_smso,
	/*  36: smul     */	vt102_s_smul,
	/*  37: ech      */	ABSENT_STRING,
	/*  38: rmacs    */	vt102_s_rmacs,
	/*  39: sgr0     */	vt102_s_sgr0,
	/*  40: rmcup    */	ABSENT_STRING,
	/*  41: rmdc     */	ABSENT_STRING,
	/*  42: rmir     */	vt102_s_rmir,
	/*  43: rmso     */	vt102_s_rmso,
	/*  44: rmul     */	vt102_s_rmul,
	/*  45: flash    */	ABSENT_STRING,
	/*  46: ff       */	ABSENT_STRING,
	/*  47: fsl      */	ABSENT_STRING,
	/*  48: is1      */	ABSENT_STRING,
	/*  49: is2      */	ABSENT_STRING,
	/*  50: is3      */	ABSENT_STRING,
	/*  51: if       */	ABSENT_STRING,
	/*  52: ich1     */	ABSENT_STRING,
	/*  53: il1      */	vt102_s_il1,
	/*  54: ip       */	ABSENT_STRING,
	/*  55: kbs      */	vt102_s_kbs,
	/*  56: ktbc     */	ABSENT_STRING,
	/*  57: kclr     */	ABSENT_STRING,
	/*  58: kctab    */	ABSENT_STRING,
	/*  59: kdch1    */	ABSENT_STRING,
	/*  60: kdl1     */	ABSENT_STRING,
	/*  61: kcud1    */	vt102_s_kcud1,
	/*  62: krmir    */	ABSENT_STRING,
	/*  63: kel      */	ABSENT_STRING,
	/*  64: ked      */	ABSENT_STRING,
	/*  65: kf0      */	vt102_s_kf0,
	/*  66: kf1      */	vt102_s_kf1,
	/*  67: kf10     */	vt102_s_kf10,
	/*  68: kf2      */	vt102_s_kf2,
	/*  69: kf3      */	vt102_s_kf3,
	/*  70: kf4      */	vt102_s_kf4,
	/*  71: kf5      */	vt102_s_kf5,
	/*  72: kf6      */	vt102_s_kf6,
	/*  73: kf7      */	vt102_s_kf7,
	/*  74: kf8      */	vt102_s_kf8,
	/*  75: kf9      */	vt102_s_kf9,
	/*  76: khome    */	ABSENT_STRING,
	/*  77: kich1    */	ABSENT_STRING,
	/*  78: kil1     */	ABSENT_STRING,
	/*  79: kcub1    */	vt102_s_kcub1,
	/*  80: kll      */	ABSENT_STRING,
	/*  81: knp      */	ABSENT_STRING,
	/*  82: kpp      */	ABSENT_STRING,
	/*  83: kcuf1    */	vt102_s_kcuf1,
	/*  84: kind     */	ABSENT_STRING,
	/*  85: kri      */	ABSENT_STRING,
	/*  86: khts     */	ABSENT_STRING,
	/*  87: kcuu1    */	vt102_s_kcuu1,
	/*  88: rmkx     */	vt102_s_rmkx,
	/*  89: smkx     */	vt102_s_smkx,
	/*  90: lf0      */	ABSENT_STRING,
	/*  91: lf1      */	vt102_s_lf1,
	/*  92: lf10     */	ABSENT_STRING,
	/*  93: lf2      */	vt102_s_lf2,
	/*  94: lf3      */	vt102_s_lf3,
	/*  95: lf4      */	vt102_s_lf4,
	/*  96: lf5      */	ABSENT_STRING,
	/*  97: lf6      */	ABSENT_STRING,
	/*  98: lf7      */	ABSENT_STRING,
	/*  99: lf8      */	ABSENT_STRING,
	/* 100: lf9      */	ABSENT_STRING,
	/* 101: rmm      */	ABSENT_STRING,
	/* 102: smm      */	ABSENT_STRING,
	/* 103: nel      */	ABSENT_STRING,
	/* 104: pad      */	ABSENT_STRING,
	/* 105: dch      */	ABSENT_STRING,
	/* 106: dl       */	ABSENT_STRING,
	/* 107: cud      */	vt102_s_cud,
	/* 108: ich      */	ABSENT_STRING,
	/* 109: indn     */	ABSENT_STRING,
	/* 110: il       */	ABSENT_STRING,
	/* 111: cub      */	vt102_s_cub,
	/* 112: cuf      */	vt102_s_cuf,
	/* 113: rin      */	ABSENT_STRING,
	/* 114: cuu      */	vt102_s_cuu,
	/* 115: pfkey    */	ABSENT_STRING,
	/* 116: pfloc    */	ABSENT_STRING,
	/* 117: pfx      */	ABSENT_STRING,
	/* 118: mc0      */	vt102_s_mc0,
	/* 119: mc4      */	vt102_s_mc4,
	/* 120: mc5      */	vt102_s_mc5,
	/* 121: rep      */	ABSENT_STRING,
	/* 122: rs1      */	ABSENT_STRING,
	/* 123: rs2      */	vt102_s_rs2,
	/* 124: rs3      */	ABSENT_STRING,
	/* 125: rf       */	ABSENT_STRING,
	/* 126: rc       */	vt102_s_rc,
	/* 127: vpa      */	ABSENT_STRING,
	/* 128: sc       */	vt102_s_sc,
	/* 129: ind      */	vt102_s_ind,
	/* 130: ri       */	vt102_s_ri,
	/* 131: sgr      */	vt102_s_sgr,
	/* 132: hts      */	vt102_s_hts,
	/* 133: wind     */	ABSENT_STRING,
	/* 134: ht       */	vt102_s_ht,
	/* 135: tsl      */	ABSENT_STRING,
	/* 136: uc       */	ABSENT_STRING,
	/* 137: hu       */	ABSENT_STRING,
	/* 138: iprog    */	ABSENT_STRING,
	/* 139: ka1      */	vt102_s_ka1,
	/* 140: ka3      */	vt102_s_ka3,
	/* 141: kb2      */	vt102_s_kb2,
	/* 142: kc1      */	vt102_s_kc1,
	/* 143: kc3      */	vt102_s_kc3,
	/* 144: mc5p     */	ABSENT_STRING,
	/* 145: rmp      */	ABSENT_STRING,
	/* 146: acsc     */	vt102_s_acsc,
	/* 147: pln      */	ABSENT_STRING,
	/* 148: kcbt     */	ABSENT_STRING,
	/* 149: smxon    */	ABSENT_STRING,
	/* 150: rmxon    */	ABSENT_STRING,
	/* 151: smam     */	vt102_s_smam,
	/* 152: rmam     */	vt102_s_rmam,
	/* 153: xonc     */	ABSENT_STRING,
	/* 154: xoffc    */	ABSENT_STRING,
	/* 155: enacs    */	vt102_s_enacs,
	/* 156: smln     */	ABSENT_STRING,
	/* 157: rmln     */	ABSENT_STRING,
	/* 158: kbeg     */	ABSENT_STRING,
	/* 159: kcan     */	ABSENT_STRING,
	/* 160: kclo     */	ABSENT_STRING,
	/* 161: kcmd     */	ABSENT_STRING,
	/* 162: kcpy     */	ABSENT_STRING,
	/* 163: kcrt     */	ABSENT_STRING,
	/* 164: kend     */	ABSENT_STRING,
	/* 165: kent     */	vt102_s_kent,
	/* 166: kext     */	ABSENT_STRING,
	/* 167: kfnd     */	ABSENT_STRING,
	/* 168: khlp     */	ABSENT_STRING,
	/* 169: kmrk     */	ABSENT_STRING,
	/* 170: kmsg     */	ABSENT_STRING,
	/* 171: kmov     */	ABSENT_STRING,
	/* 172: knxt     */	ABSENT_STRING,
	/* 173: kopn     */	ABSENT_STRING,
	/* 174: kopt     */	ABSENT_STRING,
	/* 175: kprv     */	ABSENT_STRING,
	/* 176: kprt     */	ABSENT_STRING,
	/* 177: krdo     */	ABSENT_STRING,
	/* 178: kref     */	ABSENT_STRING,
	/* 179: krfr     */	ABSENT_STRING,
	/* 180: krpl     */	ABSENT_STRING,
	/* 181: krst     */	ABSENT_STRING,
	/* 182: kres     */	ABSENT_STRING,
	/* 183: ksav     */	ABSENT_STRING,
	/* 184: kspd     */	ABSENT_STRING,
	/* 185: kund     */	ABSENT_STRING,
	/* 186: kBEG     */	ABSENT_STRING,
	/* 187: kCAN     */	ABSENT_STRING,
	/* 188: kCMD     */	ABSENT_STRING,
	/* 189: kCPY     */	ABSENT_STRING,
	/* 190: kCRT     */	ABSENT_STRING,
	/* 191: kDC      */	ABSENT_STRING,
	/* 192: kDL      */	ABSENT_STRING,
	/* 193: kslt     */	ABSENT_STRING,
	/* 194: kEND     */	ABSENT_STRING,
	/* 195: kEOL     */	ABSENT_STRING,
	/* 196: kEXT     */	ABSENT_STRING,
	/* 197: kFND     */	ABSENT_STRING,
	/* 198: kHLP     */	ABSENT_STRING,
	/* 199: kHOM     */	ABSENT_STRING,
	/* 200: kIC      */	ABSENT_STRING,
	/* 201: kLFT     */	ABSENT_STRING,
	/* 202: kMSG     */	ABSENT_STRING,
	/* 203: kMOV     */	ABSENT_STRING,
	/* 204: kNXT     */	ABSENT_STRING,
	/* 205: kOPT     */	ABSENT_STRING,
	/* 206: kPRV     */	ABSENT_STRING,
	/* 207: kPRT     */	ABSENT_STRING,
	/* 208: kRDO     */	ABSENT_STRING,
	/* 209: kRPL     */	ABSENT_STRING,
	/* 210: kRIT     */	ABSENT_STRING,
	/* 211: kRES     */	ABSENT_STRING,
	/* 212: kSAV     */	ABSENT_STRING,
	/* 213: kSPD     */	ABSENT_STRING,
	/* 214: kUND     */	ABSENT_STRING,
	/* 215: rfi      */	ABSENT_STRING,
	/* 216: kf11     */	ABSENT_STRING,
	/* 217: kf12     */	ABSENT_STRING,
	/* 218: kf13     */	ABSENT_STRING,
	/* 219: kf14     */	ABSENT_STRING,
	/* 220: kf15     */	ABSENT_STRING,
	/* 221: kf16     */	ABSENT_STRING,
	/* 222: kf17     */	ABSENT_STRING,
	/* 223: kf18     */	ABSENT_STRING,
	/* 224: kf19     */	ABSENT_STRING,
	/* 225: kf20     */	ABSENT_STRING,
	/* 226: kf21     */	ABSENT_STRING,
	/* 227: kf22     */	ABSENT_STRING,
	/* 228: kf23     */	ABSENT_STRING,
	/* 229: kf24     */	ABSENT_STRING,
	/* 230: kf25     */	ABSENT_STRING,
	/* 231: kf26     */	ABSENT_STRING,
	/* 232: kf27     */	ABSENT_STRING,
	/* 233: kf28     */	ABSENT_STRING,
	/* 234: kf29     */	ABSENT_STRING,
	/* 235: kf30     */	ABSENT_STRING,
	/* 236: kf31     */	ABSENT_STRING,
	/* 237: kf32     */	ABSENT_STRING,
	/* 238: kf33     */	ABSENT_STRING,
	/* 239: kf34     */	ABSENT_STRING,
	/* 240: kf35     */	ABSENT_STRING,
	/* 241: kf36     */	ABSENT_STRING,
	/* 242: kf37     */	ABSENT_STRING,
	/* 243: kf38     */	ABSENT_STRING,
	/* 244: kf39     */	ABSENT_STRING,
	/* 245: kf40     */	ABSENT_STRING,
	/* 246: kf41     */	ABSENT_STRING,
	/* 247: kf42     */	ABSENT_STRING,
	/* 248: kf43     */	ABSENT_STRING,
	/* 249: kf44     */	ABSENT_STRING,
	/* 250: kf45     */	ABSENT_STRING,
	/* 251: kf46     */	ABSENT_STRING,
	/* 252: kf47     */	ABSENT_STRING,
	/* 253: kf48     */	ABSENT_STRING,
	/* 254: kf49     */	ABSENT_STRING,
	/* 255: kf50     */	ABSENT_STRING,
	/* 256: kf51     */	ABSENT_STRING,
	/* 257: kf52     */	ABSENT_STRING,
	/* 258: kf53     */	ABSENT_STRING,
	/* 259: kf54     */	ABSENT_STRING,
	/* 260: kf55     */	ABSENT_STRING,
	/* 261: kf56     */	ABSENT_STRING,
	/* 262: kf57     */	ABSENT_STRING,
	/* 263: kf58     */	ABSENT_STRING,
	/* 264: kf59     */	ABSENT_STRING,
	/* 265: kf60     */	ABSENT_STRING,
	/* 266: kf61     */	ABSENT_STRING,
	/* 267: kf62     */	ABSENT_STRING,
	/* 268: kf63     */	ABSENT_STRING,
	/* 269: el1      */	vt102_s_el1,
	/* 270: mgc      */	ABSENT_STRING,
	/* 271: smgl     */	ABSENT_STRING,
	/* 272: smgr     */	ABSENT_STRING,
	/* 273: fln      */	ABSENT_STRING,
	/* 274: sclk     */	ABSENT_STRING,
	/* 275: dclk     */	ABSENT_STRING,
	/* 276: rmclk    */	ABSENT_STRING,
	/* 277: cwin     */	ABSENT_STRING,
	/* 278: wingo    */	ABSENT_STRING,
	/* 279: hup      */	ABSENT_STRING,
	/* 280: dial     */	ABSENT_STRING,
	/* 281: qdial    */	ABSENT_STRING,
	/* 282: tone     */	ABSENT_STRING,
	/* 283: pulse    */	ABSENT_STRING,
	/* 284: hook     */	ABSENT_STRING,
	/* 285: pause    */	ABSENT_STRING,
	/* 286: wait     */	ABSENT_STRING,
	/* 287: u0       */	ABSENT_STRING,
	/* 288: u1       */	ABSENT_STRING,
	/* 289: u2       */	ABSENT_STRING,
	/* 290: u3       */	ABSENT_STRING,
	/* 291: u4       */	ABSENT_STRING,
	/* 292: u5       */	ABSENT_STRING,
	/* 293: u6       */	ABSENT_STRING,
	/* 294: u7       */	ABSENT_STRING,
	/* 295: u8       */	ABSENT_STRING,
	/* 296: u9       */	ABSENT_STRING,
	/* 297: op       */	ABSENT_STRING,
	/* 298: oc       */	ABSENT_STRING,
	/* 299: initc    */	ABSENT_STRING,
	/* 300: initp    */	ABSENT_STRING,
	/* 301: scp      */	ABSENT_STRING,
	/* 302: setf     */	ABSENT_STRING,
	/* 303: setb     */	ABSENT_STRING,
	/* 304: cpi      */	ABSENT_STRING,
	/* 305: lpi      */	ABSENT_STRING,
	/* 306: chr      */	ABSENT_STRING,
	/* 307: cvr      */	ABSENT_STRING,
	/* 308: defc     */	ABSENT_STRING,
	/* 309: swidm    */	ABSENT_STRING,
	/* 310: sdrfq    */	ABSENT_STRING,
	/* 311: sitm     */	ABSENT_STRING,
	/* 312: slm      */	ABSENT_STRING,
	/* 313: smicm    */	ABSENT_STRING,
	/* 314: snlq     */	ABSENT_STRING,
	/* 315: snrmq    */	ABSENT_STRING,
	/* 316: sshm     */	ABSENT_STRING,
	/* 317: ssubm    */	ABSENT_STRING,
	/* 318: ssupm    */	ABSENT_STRING,
	/* 319: sum      */	ABSENT_STRING,
	/* 320: rwidm    */	ABSENT_STRING,
	/* 321: ritm     */	ABSENT_STRING,
	/* 322: rlm      */	ABSENT_STRING,
	/* 323: rmicm    */	ABSENT_STRING,
	/* 324: rshm     */	ABSENT_STRING,
	/* 325: rsubm    */	ABSENT_STRING,
	/* 326: rsupm    */	ABSENT_STRING,
	/* 327: rum      */	ABSENT_STRING,
	/* 328: mhpa     */	ABSENT_STRING,
	/* 329: mcud1    */	ABSENT_STRING,
	/* 330: mcub1    */	ABSENT_STRING,
	/* 331: mcuf1    */	ABSENT_STRING,
	/* 332: mvpa     */	ABSENT_STRING,
	/* 333: mcuu1    */	ABSENT_STRING,
	/* 334: porder   */	ABSENT_STRING,
	/* 335: mcud     */	ABSENT_STRING,
	/* 336: mcub     */	ABSENT_STRING,
	/* 337: mcuf     */	ABSENT_STRING,
	/* 338: mcuu     */	ABSENT_STRING,
	/* 339: scs      */	ABSENT_STRING,
	/* 340: smgb     */	ABSENT_STRING,
	/* 341: smgbp    */	ABSENT_STRING,
	/* 342: smglp    */	ABSENT_STRING,
	/* 343: smgrp    */	ABSENT_STRING,
	/* 344: smgt     */	ABSENT_STRING,
	/* 345: smgtp    */	ABSENT_STRING,
	/* 346: sbim     */	ABSENT_STRING,
	/* 347: scsd     */	ABSENT_STRING,
	/* 348: rbim     */	ABSENT_STRING,
	/* 349: rcsd     */	ABSENT_STRING,
	/* 350: subcs    */	ABSENT_STRING,
	/* 351: supcs    */	ABSENT_STRING,
	/* 352: docr     */	ABSENT_STRING,
	/* 353: zerom    */	ABSENT_STRING,
	/* 354: csnm     */	ABSENT_STRING,
	/* 355: kmous    */	ABSENT_STRING,
	/* 356: minfo    */	ABSENT_STRING,
	/* 357: reqmp    */	ABSENT_STRING,
	/* 358: getm     */	ABSENT_STRING,
	/* 359: setaf    */	ABSENT_STRING,
	/* 360: setab    */	ABSENT_STRING,
	/* 361: pfxl     */	ABSENT_STRING,
	/* 362: devt     */	ABSENT_STRING,
	/* 363: csin     */	ABSENT_STRING,
	/* 364: s0ds     */	ABSENT_STRING,
	/* 365: s1ds     */	ABSENT_STRING,
	/* 366: s2ds     */	ABSENT_STRING,
	/* 367: s3ds     */	ABSENT_STRING,
	/* 368: smglr    */	ABSENT_STRING,
	/* 369: smgtb    */	ABSENT_STRING,
	/* 370: birep    */	ABSENT_STRING,
	/* 371: binel    */	ABSENT_STRING,
	/* 372: bicr     */	ABSENT_STRING,
	/* 373: colornm  */	ABSENT_STRING,
	/* 374: defbi    */	ABSENT_STRING,
	/* 375: endbi    */	ABSENT_STRING,
	/* 376: setcolor */	ABSENT_STRING,
	/* 377: slines   */	ABSENT_STRING,
	/* 378: dispc    */	ABSENT_STRING,
	/* 379: smpch    */	ABSENT_STRING,
	/* 380: rmpch    */	ABSENT_STRING,
	/* 381: smsc     */	ABSENT_STRING,
	/* 382: rmsc     */	ABSENT_STRING,
	/* 383: pctrm    */	ABSENT_STRING,
	/* 384: scesc    */	ABSENT_STRING,
	/* 385: scesa    */	ABSENT_STRING,
	/* 386: ehhlm    */	ABSENT_STRING,
	/* 387: elhlm    */	ABSENT_STRING,
	/* 388: elohlm   */	ABSENT_STRING,
	/* 389: erhlm    */	ABSENT_STRING,
	/* 390: ethlm    */	ABSENT_STRING,
	/* 391: evhlm    */	ABSENT_STRING,
	/* 392: sgr1     */	ABSENT_STRING,
	/* 393: slength  */	ABSENT_STRING,
	/* 394: OTi2     */	ABSENT_STRING,
	/* 395: OTrs     */	ABSENT_STRING,
	/* 396: OTnl     */	ABSENT_STRING,
	/* 397: OTbc     */	ABSENT_STRING,
	/* 398: OTko     */	ABSENT_STRING,
	/* 399: OTma     */	ABSENT_STRING,
	/* 400: OTG2     */	ABSENT_STRING,
	/* 401: OTG3     */	ABSENT_STRING,
	/* 402: OTG1     */	ABSENT_STRING,
	/* 403: OTG4     */	ABSENT_STRING,
	/* 404: OTGR     */	ABSENT_STRING,
	/* 405: OTGL     */	ABSENT_STRING,
	/* 406: OTGU     */	ABSENT_STRING,
	/* 407: OTGD     */	ABSENT_STRING,
	/* 408: OTGH     */	ABSENT_STRING,
	/* 409: OTGV     */	ABSENT_STRING,
	/* 410: OTGC     */	ABSENT_STRING,
	/* 411: meml     */	ABSENT_STRING,
	/* 412: memu     */	ABSENT_STRING,
	/* 413: box1     */	ABSENT_STRING,
};
static const TERMTYPE fallbacks[2] =
{
 /* linux */
	{
		linux_alias_data,
		(char *)0,	/* pointer to string table */
		linux_bool_data,
		linux_number_data,
		linux_string_data,
#if NCURSES_XNAMES
		(char *)0,	/* pointer to extended string table */
		(char **)0,	/* ...corresponding names */
		44,		/* count total Booleans */
		39,		/* count total Numbers */
		414,		/* count total Strings */
		0,		/* count extensions to Booleans */
		0,		/* count extensions to Numbers */
		0,		/* count extensions to Strings */
#endif /* NCURSES_XNAMES */
	}
, /* vt102 */
	{
		vt102_alias_data,
		(char *)0,	/* pointer to string table */
		vt102_bool_data,
		vt102_number_data,
		vt102_string_data,
#if NCURSES_XNAMES
		(char *)0,	/* pointer to extended string table */
		(char **)0,	/* ...corresponding names */
		44,		/* count total Booleans */
		39,		/* count total Numbers */
		414,		/* count total Strings */
		0,		/* count extensions to Booleans */
		0,		/* count extensions to Numbers */
		0,		/* count extensions to Strings */
#endif /* NCURSES_XNAMES */
	}
};

NCURSES_EXPORT(const TERMTYPE *) _nc_fallback (const char *name GCC_UNUSED)
{
    const TERMTYPE	*tp;

    for (tp = fallbacks;
	 	tp < fallbacks + sizeof(fallbacks)/sizeof(TERMTYPE);
	 	tp++)
	if (_nc_name_match(tp->term_names, name, "|"))
	    return(tp);
	return((TERMTYPE *)0);
}
